config/routes.rb
DingIT::Application.routes.draw do
  resources :site_configs

  resources :photos
  
  
  resources :comments
  
  
  match "topics/node:id" => "topics#node", :as => :node_topics
  resources :topics do
    resources :comments
    put :toggle_comments_closed
    put :toggle_sticky
    
    member do
      post :reply
      post :favorite
      post :follow
      post :unfollow
    end
    collection do
      get :no_reply
      get :popular
      get :feed
      post :preview
    end
  end
  
  resources :nodes
  
  devise_for :users
  
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  
  resources :notices
  
  
  
  
  
  
  
  
  
  
  root :to => 'topics#index'
  
  
  resources :users, :path => "" do
    member do
      get :topics
      get :favorites
      get :notes
    end
  end
end

app/models/notice.rb
class Notice < ActiveRecord::Base
  resourcify
  attr_accessible :text, :title
end

app/controllers/notices_controller.rb
class NoticesController < ApplicationController
  # GET /notices
  # GET /notices.json
  def index
    @notices = Notice.all
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @notices }
    end
  end

  # GET /notices/1
  # GET /notices/1.json
  def show
    @notice = Notice.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @notice }
    end
  end

  # GET /notices/new
  # GET /notices/new.json
  def new
    @notice = Notice.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @notice }
    end
  end

  # GET /notices/1/edit
  def edit
    @notice = Notice.find(params[:id])
  end

  # POST /notices
  # POST /notices.json
  def create
    @notice = Notice.new(params[:notice])

    respond_to do |format|
      if @notice.save
        format.html { redirect_to @notice, notice: 'Notice was successfully created.' }
        format.json { render json: @notice, status: :created, location: @notice }
      else
        format.html { render action: "new" }
        format.json { render json: @notice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /notices/1
  # PUT /notices/1.json
  def update
    @notice = Notice.find(params[:id])

    respond_to do |format|
      if @notice.update_attributes(params[:notice])
        format.html { redirect_to @notice, notice: 'Notice was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @notice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notices/1
  # DELETE /notices/1.json
  def destroy
    @notice = Notice.find(params[:id])
    @notice.destroy

    respond_to do |format|
      format.html { redirect_to notices_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/notices_helper.rb
module NoticesHelper
end

app/views/notices/_form.html.slim
= form_for @notice do |f|
  - if @notice.errors.any?
    #error_explanation
      h2 = "#{pluralize(@notice.errors.count, "error")} prohibited this notice from being saved:"
      ul
        - @notice.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :text
    = f.text_area :text
  .actions = f.submit 'Save'

app/views/notices/edit.html.slim
h1 Editing notice

== render 'form'

= link_to 'Show', @notice
'|
= link_to 'Back', notices_path

app/views/notices/index.html.slim
h1 Listing notices

table
  tr
    th Title
    th Text
    th
    th
    th

  - @notices.each do |notice|
    tr
      td = notice.title
      td = notice.text
      td = link_to 'Show', notice
      td = link_to 'Edit', edit_notice_path(notice)
      td = link_to 'Destroy', notice, :confirm => 'Are you sure?', :method => :delete

br

= link_to 'New Notice', new_notice_path

app/views/notices/new.html.slim
h1 New notice

== render 'form'

= link_to 'Back', notices_path

app/views/notices/show.html.slim
p#notice = notice

p
  strong Title:
  = @notice.title
p
  strong Text:
  = @notice.text

= link_to 'Edit', edit_notice_path(@notice)
'|
= link_to 'Back', notices_path