config/routes.rb
DingIT::Application.routes.draw do
  resources :site_configs

  resources :photos
  
  
  resources :comments
  
  
  match "topics/node:id" => "topics#node", :as => :node_topics
  resources :topics do
    resources :comments
    put :toggle_comments_closed
    put :toggle_sticky
    
    member do
      post :reply
      post :favorite
      post :follow
      post :unfollow
    end
    collection do
      get :no_reply
      get :popular
      get :feed
      post :preview
    end
  end
  
  resources :nodes
  
  devise_for :users
  
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  
  resources :notices
  
  
  
  
  
  
  
  
  
  
  root :to => 'topics#index'
  
  
  resources :users, :path => "" do
    member do
      get :topics
      get :favorites
      get :notes
    end
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  include Rabel::ActiveCache
  
  belongs_to :user
  belongs_to :commentable, :polymorphic => true, :counter_cache => true

  validates :user_id, :commentable_id, :commentable_type, :content, :presence => true
  
  attr_accessible :content

  before_save :markdown_content
  after_create :touch_parent_model
  after_destroy :update_last_reply

  private
  def markdown_content
    self.content_html = MarkdownTopicConverter.format(self.content) if self.content_changed?
  end

  def touch_parent_model
    if commentable.has_attribute?(:last_replied_by) and commentable.has_attribute?(:last_replied_at)
      commentable.last_replied_by = self.user.name
      commentable.last_replied_at = self.created_at
      commentable.save
    end
    
    created_date = commentable.created_at.to_date
    if commentable.has_attribute?(:involved_at)
      commentable.touch(:involved_at) if created_date.months_since(6) > Time.zone.today
    else
      commentable.touch
    end
  end
  
  def update_last_reply
    if commentable.has_attribute?(:last_replied_by) and commentable.has_attribute?(:last_replied_at)
      if commentable.comments_count == 0
        commentable.last_replied_by = ''
        commentable.last_replied_at = ''
      else
        last_comment = commentable.try(:last_comment)
        if last_comment.present?
          commentable.last_replied_by = last_comment.user.name
          commentable.last_replied_at = last_comment.created_at
        end
      end
      commentable.save
    end
  end
end

app/controllers/comments_controller.rb
# -*- coding: utf-8 -*-
class CommentsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :find_commentable, :only => [:create, :edit]
  before_filter :find_comment_and_auth, :only => [:edit, :update, :destroy]
  
  # POST /comments
  # POST /comments.json
  def create
    @comment = @commentable.comments.build(params[:comment])
    @comment.user = current_user

    if @comment.save
      @msg = t("topics.reply_success")
    else
      @msg = @comment.errors.full_messages.join("<br />")
    end
  end
  
  # GET /comments/1/edit
  def edit
    @comment = Comment.find(params[:id])
  end
  
  # PUT /comments/1
  # PUT /comments/1.json
  def update
    @comment = Comment.find(params[:id])
    
    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to custom_path(@comment.commentable), notice: '回复更新成功' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment = Comment.find(params[:id])
    if @comment.destroy
      redirect_to(custom_path(@comment.commentable), :notice => '回帖删除成功')
    else
      redirect_to(custom_path(@comment.commentable), :notice => '程序异常，回帖删除失败')
    end
  end
  
  private
  def find_commentable
    @commentable = Topic.find(params[:topic_id])
  end
  
  def find_comment_and_auth
    @comment = Comment.find(params[:id])
    authorize! :update, @comment, :message => '你没有权限管理此回复'
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.slim
- floor = comment_counter + 1 + ((@current_page - 1) * AppConfig.pagination_comments)
div.reply
  div.pull-left.face
    = user_avatar_tag(comment.user, :normal)
  div.infos
    div.info
      span.name
        = user_name_tag(comment.user)
        = " #{floor} #{t("common.floor")}, #{time_ago_in_words(comment.created_at)}" 
      span.opts
        - if can? :update, comment
          = link_to("", edit_topic_comment_path(commentable, comment), :class => "icon-edit", 'data-uid' => comment.user_id, :title => "修改回帖")
        - if current_user  
          = link_to("", "#", 'data-floor' => floor, 'data-login' => comment.user.name, :title => t("topics.reply_this_floor"), :class => "icon-comment-alt")
    div.body    
      = raw comment.content_html

app/views/comments/_form.html.slim
= simple_form_for(@comment) do |f|
  = f.error_notification

  .form-inputs
    = f.input :user_id
    = f.input :commentable_id
    = f.input :commentable_type
    = f.input :content

  .form-actions
    = f.button :submit

app/views/comments/create.js.erb
<% if @comment.errors.blank? %>
<% @current_page = 1 %>
  if($("#replies").length == 0){
    location.href = location.href;
  }
  else {
    $("#replies .items").append('<%= escape_javascript(render("comment", :commentable => @commentable, :comment => @comment, :comment_counter => @commentable.comments_count, :display_edit => true)) %>')
    $("#replies").find(".total b").text('<%= @commentable.comments_count + 1%>');
    $("#replies .reply a.edit:last").css("display","inline-block");
    Topics.replyCallback(1,'<%= escape_javascript(@msg) %>');
  }
<% else %>
  Topics.replyCallback(0,'<%= escape_javascript(@msg) %>');
<% end %>

app/views/comments/edit.html.slim
div#page
  = render "topics/nav"
  div.container.clearfix id="main-content"
    div.row-fluid.sidebar-right
      div.span9.blog-detail.primary-column
        div.form.box#reply
          = simple_form_for([@commentable, @comment]) do |f|
            = f.error_notification
            label 回复内容：
            div.control-grounp.edit_tools
              label.control-label
                div.controls
                  = render "topics/editor_toolbar"
            = f.text_area :content, :class => "topic_editor", :rows => "20"
            div.btn-group
              = f.submit t("common.save"), :class => "btn btn-primary", 'data-disable-with' => t("common.saving")
              a href=custom_path(@commentable) class="btn"
                | #{t("common.cancel")}
            - if can? :destroy, @comment
              = link_to "删除", [@commentable, @comment], :class => "pull-right btn btn-danger", :method => :delete, :data => {:confirm => "确定要删除此回复么？"}
      div.span3.sidebar.secondary-column#secondary-nav
        div.box
          = "#{t("reply.topic_location")}："
          br
            = render_topic_title(@comment.commentable)  
        div.box
          = render_cell :topics, :reply_help_block

app/views/comments/index.html.slim
h1 Listing comments

table
  tr
    th User
    th Commentable
    th Commentable type
    th Content
    th
    th
    th

  - @comments.each do |comment|
    tr
      td = comment.user_id
      td = comment.commentable_id
      td = comment.commentable_type
      td = comment.content
      td = link_to 'Show', comment
      td = link_to 'Edit', edit_comment_path(comment)
      td = link_to 'Destroy', comment, :confirm => 'Are you sure?', :method => :delete

br

= link_to 'New Comment', new_comment_path

app/views/comments/new.html.slim
h1 New comment

== render 'form'

= link_to 'Back', comments_path

app/views/comments/show.html.slim
p#notice = notice

p
  strong User:
  = @comment.user_id
p
  strong Commentable:
  = @comment.commentable_id
p
  strong Commentable type:
  = @comment.commentable_type
p
  strong Content:
  = @comment.content

= link_to 'Edit', edit_comment_path(@comment)
'|
= link_to 'Back', comments_path