config/routes.rb
DingIT::Application.routes.draw do
  resources :site_configs

  resources :photos
  
  
  resources :comments
  
  
  match "topics/node:id" => "topics#node", :as => :node_topics
  resources :topics do
    resources :comments
    put :toggle_comments_closed
    put :toggle_sticky
    
    member do
      post :reply
      post :favorite
      post :follow
      post :unfollow
    end
    collection do
      get :no_reply
      get :popular
      get :feed
      post :preview
    end
  end
  
  resources :nodes
  
  devise_for :users
  
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  
  resources :notices
  
  
  
  
  
  
  
  
  
  
  root :to => 'topics#index'
  
  
  resources :users, :path => "" do
    member do
      get :topics
      get :favorites
      get :notes
    end
  end
end

app/models/node.rb
class Node < ActiveRecord::Base
  include Rabel::ActiveCache

  has_many :node_topic_mappings, :dependent => :destroy
  has_many :topics, :through => :node_topic_mappings

  attr_accessible :custom_html, :introduction, :key, :name
end

app/controllers/nodes_controller.rb
class NodesController < ApplicationController
  # GET /nodes
  # GET /nodes.json
  def index
    @nodes = Node.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @nodes }
    end
  end

  # GET /nodes/1
  # GET /nodes/1.json
  def show
    @node = Node.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @node }
    end
  end

  # GET /nodes/new
  # GET /nodes/new.json
  def new
    @node = Node.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @node }
    end
  end

  # GET /nodes/1/edit
  def edit
    @node = Node.find(params[:id])
  end

  # POST /nodes
  # POST /nodes.json
  def create
    @node = Node.new(params[:node])

    respond_to do |format|
      if @node.save
        format.html { redirect_to @node, notice: 'Node was successfully created.' }
        format.json { render json: @node, status: :created, location: @node }
      else
        format.html { render action: "new" }
        format.json { render json: @node.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /nodes/1
  # PUT /nodes/1.json
  def update
    @node = Node.find(params[:id])

    respond_to do |format|
      if @node.update_attributes(params[:node])
        format.html { redirect_to @node, notice: 'Node was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @node.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nodes/1
  # DELETE /nodes/1.json
  def destroy
    @node = Node.find(params[:id])
    @node.destroy

    respond_to do |format|
      format.html { redirect_to nodes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/nodes_helper.rb
module NodesHelper
  def render_node_topics_count(node)
    node.topics.count
  end
  
  def render_node_name(name, id)
    link_to(name, node_topics_path(id), :class => 'node')
  end
end

app/views/nodes/_form.html.slim
= simple_form_for(@node) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :key
    = f.input :introduction
    = f.input :custom_html

  .form-actions
    = f.button :submit

app/views/nodes/edit.html.slim
h1 Editing node

== render 'form'

= link_to 'Show', @node
'|
= link_to 'Back', nodes_path

app/views/nodes/index.html.slim
h1 Listing nodes

table
  tr
    th Name
    th Key
    th Introduction
    th Custom html
    th
    th
    th

  - @nodes.each do |node|
    tr
      td = node.name
      td = node.key
      td = node.introduction
      td = node.custom_html
      td = link_to 'Show', node
      td = link_to 'Edit', edit_node_path(node)
      td = link_to 'Destroy', node, :confirm => 'Are you sure?', :method => :delete

br

= link_to 'New Node', new_node_path

app/views/nodes/new.html.slim
h1 New node

== render 'form'

= link_to 'Back', nodes_path

app/views/nodes/show.html.slim
p#notice = notice

p
  strong Name:
  = @node.name
p
  strong Key:
  = @node.key
p
  strong Introduction:
  = @node.introduction
p
  strong Custom html:
  = @node.custom_html

= link_to 'Edit', edit_node_path(@node)
'|
= link_to 'Back', nodes_path