config/routes.rb
DingIT::Application.routes.draw do
  resources :site_configs

  resources :photos
  
  
  resources :comments
  
  
  match "topics/node:id" => "topics#node", :as => :node_topics
  resources :topics do
    resources :comments
    put :toggle_comments_closed
    put :toggle_sticky
    
    member do
      post :reply
      post :favorite
      post :follow
      post :unfollow
    end
    collection do
      get :no_reply
      get :popular
      get :feed
      post :preview
    end
  end
  
  resources :nodes
  
  devise_for :users
  
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  
  resources :notices
  
  
  
  
  
  
  
  
  
  
  root :to => 'topics#index'
  
  
  resources :users, :path => "" do
    member do
      get :topics
      get :favorites
      get :notes
    end
  end
end

app/models/topic.rb
# -*- coding: utf-8 -*-
# -*- c class="pu"oding: utf-8 -*-
class Topic < ActiveRecord::Base
  include Rabel::ActiveCache
  
  resourcify
  
  belongs_to :user
  
  has_many :node_topic_mappings, :dependent => :destroy
  has_many :nodes, :through => :node_topic_mappings
  accepts_nested_attributes_for :nodes

  has_many :comments, :as => :commentable, :dependent => :destroy
  
  validates :user_id, :title, :presence => true
  validate :require_node_id_if_any_nodes
  
  attr_accessible :title, :content, :node_ids
  before_save :markdown_content
  
  def self.sticky_topics
    ts = select('updated_at').with_sticky(true).order('updated_at DESC').first.try(:updated_at)
    return Rabel::Model::EMPTY_DATASET unless ts.present?
    count = with_sticky(true).count
    Rails.cache.fetch("topics/sticky/#{ts}-#{count}") do
      with_sticky(true).order('updated_at DESC').all
    end
  end
  
  def self.with_sticky(sticky)
    where(:sticky => sticky)
  end
  
  def self.home_topics(num)
    ts = select('updated_at').order('updated_at DESC').first.try(:updated_at)
    return Rabel::Model::EMPTY_DATASET unless ts.present?
    Rails.cache.fetch("topics/recent/#{self.count}/#{num}-#{ts}") do
      order('involved_at DESC').limit(num).all
    end
  end

  def last_comment
    self.comments.order('created_at ASC').last
  end
  
  private
  def require_node_id_if_any_nodes
    if Node.any? and self.nodes.empty?
      self.errors.add(:nodes, '请至少选择一个节点')
    end
  end

  def markdown_content
    self.content_html = MarkdownTopicConverter.format(self.content) if self.content_changed?
  end
end

app/controllers/topics_controller.rb
# -*- coding: utf-8 -*-
class TopicsController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :show, :node]
  before_filter :find_topic_and_auth, :only => [:edit, :update, :destroy]
  
  before_filter :only => [:toggle_comments_closed, :toggle_sticky] do |c|
    authorize! :manage, Topic, :message => '你没有权限管理此主题'
  end

  before_filter :init_base_breadcrumb
  
  # GET /topics
  # GET /topics.json
  def index
    @pre_page = AppConfig.pagination_topics
    if params[:page].present?
      @current_page = params[:page].to_i
    else
      @current_page = 1
    end
    @topics = Topic.cached_pagination(@current_page, @pre_page, 'updated_at')
    drop_breadcrumb(t("topics.topic_list.hot_topic"))
    set_seo_meta("","#{AppConfig.app_name}#{t("menu.topics")}")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @topics }
    end

  end
  
  # GET /topics/1
  # GET /topics/1.json
  def show
    @topic = Topic.find_cached(params[:id])
    store_location
    
    ActiveRecord::Base.connection.execute("UPDATE topics SET hit = hit + 1 WHERE topics.id = #{@topic.id}")
    
    @total_comments = @topic.comments_count
    @total_pages = (@total_comments * 1.0 / AppConfig.pagination_comments.to_i).ceil
    # @current_page = params[:p].nil? ? @total_pages : params[:p].to_i
    @current_page = params[:p].nil? ? 1 : params[:p].to_i
    @per_page = AppConfig.pagination_comments.to_i
    @comments = @topic.cached_assoc_pagination(:comments, @current_page, @per_page, 'created_at', Rabel::Model::ORDER_ASC)
    @new_comment = @topic.comments.new

    set_seo_meta("#{@topic.title} &raquo; #{t("menu.topics")}")
    drop_breadcrumb t("topics.read_topic")
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @topic }
    end
  end
  
  # GET /topics/new
  # GET /topics/new.json
  def new
    @topic = Topic.new
    if !params[:node].blank?
      @node = Node.find(params[:node])
      if @node.blank?
        render_404
      end
      drop_breadcrumb("#{@node.name}", node_topics_path(@node.id))
    end
    drop_breadcrumb t("topics.post_topic")
    set_seo_meta("#{t("topics.post_topic")} &raquo; #{t("menu.topics")}")
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @topic }
    end
  end
  
  # GET /topics/1/edit
  def edit
    @topic = Topic.find(params[:id])
    drop_breadcrumb t("topics.edit_topic")
    set_seo_meta("#{t("topics.edit_topic")} &raquo; #{t("menu.topics")}")
  end
  
  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(params[:topic])
    @topic.user = current_user
    
    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic, notice: '文章创建成功' }
        format.json { render json: @topic, status: :created, location: @topic }
      else
        format.html { render action: "new" }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # PUT /topics/1
  # PUT /topics/1.json
  def update
    @topic = Topic.find(params[:id])
    
    respond_to do |format|
      if @topic.update_attributes(params[:topic])
        format.html { redirect_to @topic, notice: '文章更新成功' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic = Topic.find(params[:id])
    @topic.destroy
    
    respond_to do |format|
      format.html { redirect_to topics_url }
      format.json { head :no_content }
    end
  end
  
  def toggle_comments_closed
    @topic = Topic.find(params[:topic_id])
    @topic.toggle!(:comments_closed)
    @topic.touch
    redirect_to @topic, notice: '关闭回复成功'
  end
  
  def toggle_sticky
    @topic = Topic.find(params[:topic_id])
    @topic.toggle!(:sticky)
    @topic.touch
    redirect_to @topic, notice: '置顶文章成功'
  end

  def node
    
    pre_page = AppConfig.pagination_topics
    if params[:page].present?
      current_page = params[:page].to_i
    else
      current_page = 1
    end
    
    @node = Node.find(params[:id])
    @topics = @node.cached_assoc_pagination(:topics, current_page, pre_page, 'updated_at')
    drop_breadcrumb("#{@node.name}")
    render :action => "index"
  end

  def preview
    @body = params[:body]

    respond_to do |format|
      format.json
    end
  end
    
  private
  def find_topic_and_auth
    @topic = Topic.find(params[:id])
    authorize! :update, @topic, :message => '你没有权限管理此主题'
  end

  def init_base_breadcrumb
    drop_breadcrumb(t("menu.topics"), topics_path)
  end
end

app/helpers/topics_helper.rb
# coding: utf-8
require 'digest/md5'

module TopicsHelper
  def format_topic_body(text)
    MarkdownTopicConverter.format(text)
  end

  def topic_use_readed_text(state)
    case state
    when true
      t("topics.have_no_new_reply")
    else
      t("topics.has_new_replies")
    end
  end

  def topic_favorite_tag(topic)
    return "" if current_user.blank?
    class_name = "bookmark"
    link_title = "收藏"
    if current_user and current_user.favorite_topic_ids.include?(topic.id)
      class_name = "bookmarked"
      link_title = "取消收藏"
    end

    link_to "", "#", :onclick => "return Topics.favorite(this);", 'data-id' => topic.id, :class => "icon small_#{class_name}", :title => link_title, :rel => "twipsy"
  end

  def topic_follow_tag(topic)
    return "" if current_user.blank?
    return "" if topic.blank?
    return "" if owner?(topic)
    class_name = "follow"
    if topic.follower_ids.include?(current_user.id)
      class_name = "followed"
    end
    icon = content_tag("i", "", :class => "icon small_#{class_name}")
    link_to raw([icon,"关注"].join(" ")), "#", :onclick => "return Topics.follow(this);",
                        'data-id' => topic.id,
                        'data-followed' => (class_name == "followed"),
                        :rel => "twipsy"
  end

  def render_topic_title(topic)
    return t("topics.topic_was_deleted") if topic.blank?
    link_to(topic.title, topic_path(topic), :title => topic.title)
  end

  def render_topic_last_reply_time(topic)
    l((topic.replied_at || topic.created_at), :format => :short)
  end

  def render_topic_created_at(topic)
    timeago(topic.created_at, :class => "published")
  end

  def render_topic_last_be_replied_time(topic)
    timeago(topic.replied_at)
  end

  def render_topic_node_select_tag(topic)
    return if topic.blank?
    grouped_collection_select :topic, :node_id, Section.all,
                    :sorted_nodes, :name, :id, :name, {:value => topic.node_id,
                    :include_blank => true, :prompt => "选择节点"}, :style => "width:145px;"
  end
end

app/views/topics/_comment_form.html.slim
= form_for([@topic, @new_comment], :remote => true) do |f|
  = f.text_area :content, :class => "topic_editor", :rows => "5", :tabindex => "1"
  = f.submit t("topics.submit_reply"), :class => 'btn btn-primary', :tabindex => "2", :data => { :disable_with => "正在提交"}
  span.help-inline
    | Ctrl+Enter

app/views/topics/_form.html.slim
= simple_form_for(@topic) do |f|
  = f.error_notification
  h4
    | 所属节点
    small.muted
      | （至少选择一个）
  - Node.all.each do |node|
    label.checkbox.inline
      - if @topic.nodes.include?(node) or Node.count == 1
        = check_box_tag 'topic[node_ids][]', node.id, :checked => true
      - else
        = check_box_tag 'topic[node_ids][]', node.id
      = label_tag node.name
  = f.input :title do
    = f.text_field :title, :style => "width:100%;"
  = f.label :content

  div.control-grounp.edit_tools
    label.control-label
      div.controls
        = render "editor_toolbar"
        
  = f.text_area :content, :class => "topic_editor", :rows => "5", :tabindex => "1"

  div.btn-group
    = f.submit t("common.save"), :class => "btn btn-primary", 'data-disaable-with' => t("common.saving")
    = link_to(t("common.cancel"), @topic.id.blank? ? topics_path : topic_path(@topic), :class => "btn")

app/views/topics/_node_info.html.slim
- if !node.blank?
  div
    h2
      | #{node.name}
    span.total  
      | 共有 #{render_node_topics_count(node)} 个讨论主题
- else        
  div.sorts
    span.lb
      | 查看：
    ul    
      li class=(action_name == "index" ? 'active' : nil)
        = link_to "默认", topics_path
      li class=(action_name == "popular" ? 'active' : nil)
        i.icon-heart
        = link_to "优质帖子", popular_topics_path, :class => "popular"

app/views/topics/_sidebar_for_gadget.html.slim
#ruby-group-promote.box
  #feedGadget Loading...
- content_for(:scripts) do
  /! welcome page sidebar js
  script{:src => "http://www.google.com/jsapi/?key=# Setting.google_js_api_key}" type="text/javascript"
  = javascript_include_tag("gfdynamicfeedcontrol")
  javascript:
    | function showGadget() {
      | var feeds = [
       | {title:'#{t("common.hot_topics")}',
        | url:'#{Setting.external_feed_url}'}];

      | new GFdynamicFeedControl(feeds, 'feedGadget',
                               | {numResults : 5, stacked : true,
                                | title: "#{Setting.external_feed_name}"});
    | }
    | google.load("feeds", "1");
    | google.setOnLoadCallback(showGadget);

app/views/topics/_sidebar_for_help.slim
aside.widget.cleanfix
  #topic_new_tip.box
    h2= t("topics.tips_for_create_topic")
    span.body.help-block
      = render_cell :topics, :reply_help_block

app/views/topics/_sidebar_for_new_topic.html.slim
.sidebar
  = render_cell :topics, :sidebar_for_new_topic_node, { :node => @node }
  #topic_new_tip.box
    h2= t("topics.tips_for_create_topic")
    span.body.help-block
      = render_cell :topics, :reply_help_block

app/views/topics/_sidebar_for_topic_index.html.slim
= render_cell :topics, :sidebar_sticky_topics

app/views/topics/_sidebar_for_topic_recent.html.slim
= render_cell :topics, :sidebar_for_new_topic_button_group
= raw SiteConfig.topic_index_sidebar_html
= render :partial => "sidebar_for_gadget"
= render_cell :topics, :sidebar_hot_nodes

app/views/topics/_topic_info.html.slim
div.infos
  div.pull-right.avatar_large
    = user_avatar_tag(topic.user, :normal)
    
  h.entry-title  
    = truncate(topic.title, :length => 100)
  div.info.leader
    - topic.nodes.each do |node|
      = render_node_name(node.name, node.id)
    = user_name_tag(topic.user, :data => { :author => true })
    = raw t("common.created_at", :time => time_ago_in_words(topic.created_at))
    - if !topic.last_replied_by.blank?
      = " #{t("common.last_by")} #{topic.last_replied_by} #{raw t("common.reply_at", :time => time_ago_in_words(topic.last_replied_at))}"
    = " 共#{topic.hit}#{t("common.read_times")}"

app/views/topics/_topic_tools.html.slim
div.tools.pull-right
  - if can? :update, topic
    = link_to "", edit_topic_path(topic), :class => "icon-pencil", :title => "修改本帖"
  - if can? :destroy, topic
    = link_to "", topic_path(topic), :method => :delete, 'data-confirm' => t("common.confirm_delete"), :class => "icon-remove", :title => "删除本帖"
  - if can? :manage, topic
    - toggle_comments_closed_tip = topic.comments_closed? ? '允许回复' : '禁止回复'
    = link_to toggle_comments_closed_tip, topic_toggle_comments_closed_path(topic), :method => :put, :title => toggle_comments_closed_tip
    - toggle_sticky_tip = topic.sticky? ? '取消置顶' : '置顶此话题'
    = link_to toggle_sticky_tip, topic_toggle_sticky_path(topic), :method => :put, :title => toggle_sticky_tip

app/views/topics/edit.html.slim
div#page
  == render "topics/nav"
  div.container.clearfix id="main-content"
    div.row-fluid.sidebar-right
      div.span9.blog-detail.primary-column
        div.form.box#reply
          == render 'form'
      div.span3.sidebar.secondary-column#secondary-nav
        = render "sidebar_for_help"

app/views/topics/new.html.slim
div#page
  == render "topics/nav"
  div.container.clearfix id="main-content"
    div.row-fluid.sidebar-right
      div.span9.blog-detail.primary-column
        div.form.box#reply
          == render 'form'
      div.span3.sidebar.secondary-column#secondary-nav
        = render "sidebar_for_help"

app/views/topics/preview.json.slim
= {:body => format_topic_body(@body)}.to_json.html_safe

app/views/topics/show.html.slim
div#page
  = render "topics/nav"
  div.container.clearfix id="main-content"
    div.row-fluid.sidebar-right
      div.span9.blog-detail.primary-column
        div.topics.box.hfeed#topic_show
          div.topic.hentry
            = render :partial => "topics/topic_info", :locals => { :topic => @topic }
            div.body
              = raw @topic.content_html
            = render :partial => "topics/topic_tools", :locals => { :topic => @topic }
            = social_share_button_tag("#{@topic.title} via: @#{AppConfig.twitter_id}")

        - if @topic.comments_count == 0
          div.no_result
            = t("topics.no_replies")
        - else
          div.box.box_gray#replies
            div.total
              | 共收到
              b
                = @topic.comments_count
              | 条回复
            div.items
              = render @comments, :commentable => @topic
            - if @total_pages > 1
              = paginate @comments, :param_name => :p, :outer_window => 3
        - if current_user
          div.form.box#reply
            = render "editor_toolbar"
            = render "comment_form"
            span.body.helpblock
      div.span3.sidebar.secondary-column#secondary-nav
        = render "sidebar_for_help"